### ISSUE TITLE
Scroll Bar

### ISSUE THREAD

**Issue by luwol3** [E-Edu/frontend#283]
I have the problem that on some pages a scrollbar is displayed at the bottom. 
![grafik](https://user-images.githubusercontent.com/60048565/79063446-034ac780-7ca2-11ea-8984-7f844c1ff39d.png)
This applies everywhere except on the home page; Add teacher; Reports; Settings page.

**Comment by luwol3** [comment]
Sorry I forgot to giv my screen details. My screen is a 4:3 screen and it has a resolution of 1280x1024px.

**Comment by luwol03** [comment]
i still have that problem. It's not fixed yet.

**Comment by msentwickler** [comment]
Yeah, if you are on master than it's not merged
