### ISSUE TITLE
Landing Page - font

### ISSUE THREAD

**Issue by Akida31** [E-Edu/frontend#33]
# Description 
Change the fonts on the landing page. 
# Suggestion
Look to Adobe XD

**Comment by Akida31** [comment]
@import url("https://fonts.googleapis.com/css?family=Arimo&display=swap%22);
@import url("https://fonts.googleapis.com/css?family=Hind+Siliguri&display=swap%22);
font-family: "Arimo", sans-serif;
font-family: "Hind Siliguri", sans-serif;

**Comment by TimyStream** [comment]
MainCSS => "Hind Siliguri" =>  [body] -> Font
MainCSS => "Arimo" => [class] -> ".font-Arimo"

**Comment by adrian-goe** [comment]
Done with new landigpage
